const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'America/Los_Angeles'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.request.post('http://127.0.0.1:4178/__reset');
 await page.goto('http://127.0.0.1:4178/#assignments');
 await page.locator('#v-assignments').waitFor({state:'visible'});
 assert.equal(await page.locator('.workload-person').count(),10);
 assert.equal(await page.locator('#assignment-tasks .assignment-task').count(),4);
 assert.match(await page.locator('#assignment-summary').innerText(),/14 active projects/);
 assert.match(await page.locator('#assignment-summary').innerText(),/1 waiting for feedback hidden/);
 assert.match(await page.locator('#assignment-context').innerText(),/Moodboarding.*Atlas/s);
 assert.match(await page.locator('#assignment-context').innerText(),/Red Flag/);
 assert.match(await page.locator('#assignment-context').innerText(),/Due [A-Z][a-z]{2} \d{1,2}/);
 assert.match(await page.locator('#assignment-tasks .assignment-task').first().innerText(),/Due [A-Z][a-z]{2} \d{1,2}/);
 assert.doesNotMatch(await page.locator('#assignment-tasks').innerText(),/Bloom/);
 assert.doesNotMatch(await page.locator('#assignment-tasks .assignment-task').filter({hasText:'Atlas'}).innerText(),/Active now/);
 assert.match(await page.locator('.workload-person').first().innerText(),/Ella Brooks/);
 assert.doesNotMatch(await page.locator('[data-member="ella"]').innerText(),/Motion designer/);
 assert.match(await page.locator('[data-member="ella"] .person-skills').innerText(),/Motion.*Video/s);
 assert.match(await page.locator('[data-member="alex"]').innerText(),/3 active/);
 assert.match(await page.locator('[data-member="alex"]').innerText(),/Arc.*Cedar.*Fieldwork/s);
 assert.equal(await page.locator('[data-member="alex"] .workload-projects').evaluate(el=>getComputedStyle(el).flexDirection),'column');
 const bloom=page.locator('#assignment-tasks .assignment-task').filter({hasText:'Bloom'});
 await page.locator('#include-feedback').check();
 assert.match(await page.locator('#assignment-tasks .assignment-task').last().innerText(),/Bloom/);
 assert.equal(await bloom.locator('.queue-avatar').count(),1);
 assert.match(await bloom.locator('.queue-avatar').innerText(),/JL/);
 assert.doesNotMatch(await bloom.innerText(),/Jordan/);
 assert.equal(await bloom.locator('.queue-task-tag').count(),1);
 assert.match(await bloom.innerText(),/Waiting for Feedback/);
 await page.locator('#assignment-search').fill('feedback');
 assert.equal(await page.locator('#assignment-tasks .assignment-task').count(),1);
 assert.match(await page.locator('#assignment-tasks').innerText(),/Bloom/);
 await page.locator('#assignment-search').fill('');
 await page.locator('#include-feedback').uncheck();
 assert.doesNotMatch(await page.locator('#assignment-tasks').innerText(),/Bloom/);
 await page.screenshot({animations:'disabled',path:'/private/tmp/hex-assignments-redesign.png'});
 // Staffing is explicit: two people can be assigned while more help is needed.
 assert.equal(await page.locator('#assignment-context').getByRole('switch',{name:'Fully staffed'}).isDisabled(),true);
 await page.locator('[data-member="zoe"] .assign-action').click();
 await page.locator('[data-member="maya"] .assign-action').click();
 assert.match(await page.locator('#assignment-summary').innerText(),/4 current tasks need staffing/);
 assert.match(await page.locator('.workload-group-label').first().innerText(),/ASSIGNED.*2/s);
 assert.match(await page.locator('.workload-person').first().innerText(),/Maya Chen/);
 assert.match(await page.locator('.workload-person').nth(1).innerText(),/Zoe Kim/);
 assert.match(await page.locator('.workload-group-label').nth(1).innerText(),/REMAINING TEAM.*8/s);
 assert.equal(await page.locator('.workload-group-label').nth(1).evaluate(el=>getComputedStyle(el).borderTopStyle),'none');
 await page.locator('#assignment-context').getByRole('switch',{name:'Fully staffed'}).check();
 assert.match(await page.locator('#assignment-summary').innerText(),/3 current tasks need staffing/);
 await page.reload();await page.locator('#v-assignments').waitFor({state:'visible'});
 await page.locator('#queue-current').click();
 await page.locator('#assignment-tasks .assignment-task').filter({hasText:'Atlas'}).click();
 assert.equal(await page.locator('#assignment-context').getByRole('switch',{name:'Fully staffed'}).isChecked(),true);
 // Removing one person reopens staffing even if someone else remains. Undo restores both.
 await page.locator('[data-member="maya"] .assign-action').click();
 assert.match(await page.locator('.workload-group-label').first().innerText(),/ASSIGNED.*1/s);
 assert.match(await page.locator('#assignment-summary').innerText(),/4 current tasks need staffing/);
 await page.locator('#assignment-feedback').getByRole('button',{name:'Undo',exact:true}).click();
 assert.equal(await page.locator('#assignment-context').getByRole('switch',{name:'Fully staffed'}).isChecked(),true);
 assert.match(await page.locator('.workload-group-label').first().innerText(),/ASSIGNED.*2/s);
 await page.locator('#assignment-detail').click();
 assert.equal(await page.locator('#dp-staffing').getByRole('switch',{name:'Fully staffed'}).isChecked(),true);
 await page.locator('#dp-staffing').getByRole('switch',{name:'Fully staffed'}).uncheck();
 await page.locator('#del-panel .btn-close').click();
 assert.equal(await page.locator('#assignment-context').getByRole('switch',{name:'Fully staffed'}).isChecked(),false);
 // Assigned people move to the top for every selected task.
 await page.locator('#assignment-tasks .assignment-task').filter({hasText:'Kinfolk'}).click();
 assert.match(await page.locator('.workload-group-label').first().innerText(),/ASSIGNED.*1/s);
 assert.match(await page.locator('.workload-person').first().innerText(),/Leo Park/);
 await page.locator('[data-member="kai"] .assign-action').click();
 await page.reload();await page.locator('#v-assignments').waitFor({state:'visible'});
 await page.locator('#queue-current').click();
 assert.equal(await page.locator('#assignment-tasks .assignment-task').count(),14);
 await page.locator('#assignment-tasks .assignment-task').filter({hasText:'Kinfolk'}).click();
 assert.equal(await page.locator('[data-member="kai"] .assign-action').innerText(),'Remove');
 await page.locator('[data-member="kai"] .assign-action').click();
 assert.equal(await page.locator('[data-member="kai"] .assign-action').innerText(),'Assign');
 // Workload project links choose the correct task; task details still open.
 await page.locator('[data-member="alex"] .workload-projects').getByRole('button',{name:'Cedar · Brand dev',exact:true}).click();
 assert.match(await page.locator('#assignment-context').innerText(),/Brand Development.*Cedar/s);
 await page.locator('#assignment-detail').click();
 assert.match(await page.locator('#dp-title').innerText(),/Brand Development/);
 await page.locator('#del-panel .btn-close').click();
 // Plan ahead is collapsed by default, and retains all team comparisons.
 assert.equal(await page.locator('#assignment-upcoming').getAttribute('open'),null);
 await page.locator('#upcoming-label').click();
 await page.locator('#upcoming-tasks .assignment-task').first().click();
 assert.equal(await page.locator('.workload-person').count(),10);
 // Smaller desktop layout remains readable without page overflow.
 await page.setViewportSize({width:1280,height:900});
 await page.screenshot({animations:'disabled',path:'/private/tmp/hex-assignments-1280.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.ni').filter({hasText:'Team'}).click();
 await page.locator('#team-core .tc').filter({hasText:'Alex Morgan'}).waitFor();
 assert.match(await page.locator('#team-core .tc').filter({hasText:'Alex Morgan'}).innerText(),/Due [A-Z][a-z]{2} \d{1,2}/);
 assert.deepEqual(errors,[]);
 await page.request.post('http://127.0.0.1:4178/__reset');
 await browser.close();console.log('Assignments passed: avatar queue, deliverable tags, assigned-first grouping, skill tags, multi-person staffing, undo, persistence, workload, task details, upcoming, layout.');
})().catch(e=>{console.error(e);process.exit(1);});
