const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'America/Los_Angeles'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.request.post('http://127.0.0.1:4178/__reset');
await page.goto('http://127.0.0.1:4178');
await page.locator('.tr').filter({hasText:'Acme Studio'}).waitFor();
assert.match(await page.locator('.tr').filter({hasText:'Acme Studio'}).innerText(),/Moodboarding/);
await page.locator('.tr').filter({hasText:'Acme Studio'}).click();
assert.match(await page.locator('#cp-pace').innerText(),/4 days behind plan/);
assert.match(await page.locator('#cp-pace').innerText(),/Brand Explorations/);
await page.locator('#client-panel').getByRole('button',{name:'Red Flag',exact:true}).click();
await page.locator('#client-panel').getByRole('button',{name:'Red Flag',exact:true}).click();
await page.screenshot({animations:'disabled',path:'/private/tmp/hex-project-pace.png'});
const priorFinish=await page.locator('#cp-end-input').inputValue();
const revised=new Date(priorFinish+'T00:00:00');revised.setDate(revised.getDate()+3);
const revisedValue=revised.toLocaleDateString('en-CA');
await page.locator('#cp-end-input').fill(revisedValue);
await page.locator('#cp-end-input').press('Tab');
assert.equal(await page.locator('#cp-end-input').inputValue(),revisedValue);
await page.locator('#cp-del-list > div').filter({hasText:'Moodboarding'}).click();
assert.match(await page.locator('#deliverable-timing').innerText(),/Clock running/);
await page.screenshot({animations:'disabled',path:'/private/tmp/hex-deliverable-timing.png'});
await page.locator('#dp-complete-btn').click();
assert.match(await page.locator('#deliverable-timing').innerText(),/Completed/);
await page.locator('#del-panel .btn-close').click();
assert.match(await page.locator('#cp-sub').innerText(),/Brand Explorations/);
await page.locator('#client-panel .btn-close').click();
await page.locator('.ni').filter({hasText:'Assignments'}).click();
assert.match(await page.locator('#assignment-summary').innerText(),/Need assignment/);
const task=page.locator('.assignment-task').filter({hasText:'Acme Studio'}).filter({hasText:'Brand Explorations'});
await task.locator('select').selectOption('jordan');
await task.getByRole('button',{name:'Jordan Lee ×'}).waitFor();
assert.match(await page.locator('.workload-person').filter({hasText:'Jordan Lee'}).innerText(),/1 active/);
await page.screenshot({animations:'disabled',path:'/private/tmp/hex-assignments.png'});
await page.reload();
await page.locator('.tr').filter({hasText:'Acme Studio'}).waitFor();
assert.match(await page.locator('.tr').filter({hasText:'Acme Studio'}).innerText(),/Brand Explorations/);
await page.locator('.ni').filter({hasText:'Assignments'}).click();
await page.locator('.assignment-task').filter({hasText:'Acme Studio'}).filter({hasText:'Brand Explorations'}).getByRole('button',{name:'Jordan Lee ×'}).waitFor();
await page.locator('#assignment-filter').selectOption('unassigned');
assert.ok((await page.locator('.assignment-task').count())>0);
assert.equal(await page.locator('.assignment-chip').count(),0);
await page.getByRole('button',{name:'Timeline',exact:true}).click();
await page.locator('.tl-bar').first().waitFor();
await page.screenshot({animations:'disabled',path:'/private/tmp/hex-timeline.png'});
// Reopen from the timeline project panel, then verify downstream reset.
await page.locator('.tl-name-row').filter({hasText:'Acme Studio'}).click();
await page.locator('#proj-panel').getByRole('button',{name:'Need to Assign',exact:true}).click();
await page.locator('#pp-del-list > div').filter({hasText:'Moodboarding'}).click();
page.once('dialog',d=>d.accept());
await page.locator('#dp-complete-btn').click();
assert.match(await page.locator('#deliverable-timing').innerText(),/Clock running/);
await page.locator('#del-panel .btn-close').click();
await page.locator('#proj-panel .btn-close').click();
await page.locator('.ni').filter({hasText:'Assignments'}).click();
await page.locator('#assignment-filter').selectOption('all');
const brand=page.locator('.assignment-task').filter({hasText:'Acme Studio'}).filter({hasText:'Brand Explorations'});
assert.match(await brand.innerText(),/Upcoming/);
await brand.locator('.assignment-task-title').click();
assert.equal(await page.locator('#dp-complete-btn').isDisabled(),true);
assert.match(await page.locator('#deliverable-timing').innerText(),/Not started/);
await page.locator('#del-panel .btn-close').click();
// Newly created projects can be assigned immediately, without a reload.
await page.locator('#btn-new-main').click();
await page.locator('#client-name').fill('New Test Client');
await page.locator('#kickoff-date').fill('2026-09-01');
await page.locator('.pkg-card').filter({hasText:'Full Brand'}).first().click();
await page.locator('#panel').getByRole('button',{name:'Create Project',exact:true}).click();
await page.locator('#v-timeline').waitFor({state:'visible'});
await page.locator('.ni').filter({hasText:'Assignments'}).click();
const created=page.locator('.assignment-task').filter({hasText:'New Test Client'}).filter({hasText:'Moodboarding'});
await created.locator('select').selectOption('jordan');
await created.getByRole('button',{name:'Jordan Lee ×'}).waitFor();
assert.equal(errors.length,0,errors.join('\n'));
await browser.close();console.log('Browser workflow passed: pace, clock, completion, assignment, workload, persistence, filters, timeline.');
})().catch(e=>{console.error(e);process.exit(1);});
